M48
; DRILL file {KiCad 7.0.5} date Sat Aug 12 02:06:33 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-12T02:06:33+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0295
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0454
%
G90
G05
T1
X4.0831Y-3.7169
X4.1769Y-3.6628
T2
X4.0892Y-2.9546
X4.1483Y-2.8524
T3
X4.3472Y-2.5051
X4.3472Y-4.0972
X5.7055Y-3.3
T0
M30
