M48
; DRILL file {KiCad 7.0.5} date Tue Aug  8 00:54:53 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-08T00:54:53+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0295
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.0454
%
G90
G05
T1
X5.3769Y-2.8772
X5.4556Y-3.0135
T2
X4.0831Y-3.7169
X4.1769Y-3.6628
T3
X4.0892Y-2.9546
X4.1483Y-2.8524
T4
X4.3472Y-2.5051
X4.3472Y-4.0972
X5.7055Y-3.3
T0
M30
